Repository HadoukenIO/js-adapter, pull requests merged in 2018-11, with the labels that each got.

#200 RUN-4712 Add API to associate app log with custom username
  src/api/application/application.ts
  test/application.test.ts
  tutorials/Application.setAppLogUsername.md
Labels: cla-present

#202 RUN-4727 Update the tutorial for System.getProxySettings
  tutorials/System.getProxySettings.md
Labels: cla-present

#201 RUN-4647 definitely typed: move shapes from v1 to v2
  src/api/application/application.ts
  src/api/application/applicationOption.ts
  src/api/base.ts
  src/api/events/application.ts
  src/api/events/base.ts
  src/api/system/application.ts
  src/api/system/external-process.ts
  src/api/system/host-specs.ts
  src/api/system/process.ts
  src/api/system/proxy.ts
  src/api/system/rvm.ts
  src/api/system/system.ts
  src/api/system/window.ts
  src/api/window/anchor-type.ts
  src/api/window/window.ts
  src/api/window/windowOption.ts
Labels: auto testing done, cla-present

#203 RUN-4677 - Channel lifecycle
  src/api/interappbus/channel/channel.ts
  src/api/interappbus/channel/client.ts
  src/api/interappbus/channel/index.ts
  src/api/interappbus/channel/provider.ts
Labels: auto testing done, cla-present

#204 RUN-4730 listener callback not implemented in launchExternalProcess
  src/api/system/system.ts
  test/system.test.ts
Labels: auto testing done, cla-present

#205 RUN-4729 Add missing global shapes doc
  src/api/system/monitor.ts
  src/api/system/system.ts
  src/api/window/window.ts
Labels: auto testing started, cla-present

#206 RUN-4737 add listener implementation in monitor external process
  src/api/system/system.ts
  tutorials/System.monitorExternalProcess.md
Labels: auto testing done, cla-present
