Repository HadoukenIO/js-adapter, pull requests merged in 2018-12, with the labels that each got.

#209 Switch to SSH
  .gitmodules
Labels: auto testing ignore, cla-present

#210 Merge staging into develop
  .gitmodules
Labels: cla-present

#208 RUN-4758 build fix
  Gruntfile.js
  package-lock.json
  package.json
Labels: auto testing done, cla-present

#211 updated installer
  resources/win/OpenFinInstaller.exe
Labels: auto testing done, cla-present

#213 RUN-4841 Add missing function Window.navigateForward
  src/api/window/window.ts
  test/window.test.ts
  tutorials/Window.navigateForward.md
Labels: auto testing done, cla-present

#214 Fixed issue where the core would use these function within events
  src/api/base.ts
Labels: cla-present

#215 RUN-4829 naming change from 'frame' to 'userMovement'
  docs.README.md
  src/api/events/window.ts
  src/api/window/window.ts
  test/window.test.ts
  tutorials/Window.disableFrame.md
  tutorials/Window.enableFrame.md
Labels: auto testing done, cla-present

#219 add back webpack alias
  Gruntfile.js
Labels: auto testing done, cla-present

#221 Move doc generation commands to script
  script/of_ci_upload_docs.py
Labels: cla-present

#217 RUN-4834 Updated Ack to send logId in a data payload
  src/api/application/application.ts
  tutorials/Application.sendApplicationLog.md
Labels: auto testing done, cla-present
