Repository HadoukenIO/js-adapter, pull requests merged in 2019-01, with the labels that each got.

#218 RUN-4833 Fix some misc known issues
  docs.README.md
  src/api/application/application.ts
  src/transport/port-discovery.ts
Labels: auto testing done, cla-present

#225 Feature/0.38.1 release
  package-lock.json
  package.json
  src/api/application/application.ts
  tutorials/Application.sendApplicationLog.md
Labels: auto testing ignore, cla-present

#231 RUN-4948 - V2 docs improvements
  docs.README.md
  src/api/interappbus/channel/channels-docs.ts
Labels: auto testing done, cla-present, documentation

#232 RUN-4848 use tutorial page url in examples
  docs.README.md
  src/api/application/application.ts
  src/api/clipboard/clipboard.ts
  src/api/interappbus/interappbus.ts
  src/api/notification/notification.ts
  src/api/system/system.ts
  src/api/window/window.ts
  tutorials/Application.create.md
  tutorials/Application.getParentUuid.md
  tutorials/Application.getWindow.md
  tutorials/Application.run.md
  tutorials/Application.setShortcuts.md
  tutorials/Notification.close.md
  tutorials/Notification.create.md
  tutorials/Notification.sendMessage.md
  tutorials/Notification.show.md
  tutorials/System.openUrlWithBrowser.md
  tutorials/Window.blur.md
  tutorials/Window.bringToFront.md
  tutorials/Window.close.md
  tutorials/Window.create.md
  tutorials/Window.disableUserMovement.md
  tutorials/Window.enableUserMovement.md
  tutorials/Window.executeJavaScript.md
  tutorials/Window.flash.md
  tutorials/Window.focus.md
  tutorials/Window.getAllFrames.md
  tutorials/Window.getBounds.md
  tutorials/Window.getGroup.md
  tutorials/Window.getInfo.md
  tutorials/Window.getNativeId.md
  tutorials/Window.getOptions.md
  tutorials/Window.getParentApplication.md
  tutorials/Window.getParentWindow.md
  tutorials/Window.getState.md
  tutorials/Window.getZoomLevel.md
  tutorials/Window.hide.md
  tutorials/Window.isShowing.md
  tutorials/Window.joinGroup.md
  tutorials/Window.leaveGroup.md
  tutorials/Window.maximize.md
  tutorials/Window.mergeGroups.md
  tutorials/Window.moveBy.md
  tutorials/Window.moveTo.md
  tutorials/Window.navigate.md
  tutorials/Window.reload.md
  tutorials/Window.resizeBy.md
  tutorials/Window.resizeTo.md
  tutorials/Window.restore.md
  tutorials/Window.setAsForeground.md
  tutorials/Window.setBounds.md
  tutorials/Window.setZoomLevel.md
  tutorials/Window.show.md
  tutorials/Window.showAt.md
  tutorials/Window.stopFlashing.md
  tutorials/Window.wrap.md
  tutorials/Window.wrapSync.md
Labels: auto testing done, cla-present, documentation

#233 Doc changes for Options and constructor warning.
  src/api/application/application.ts
  src/api/window/window.ts
Labels: auto testing done, cla-present, documentation

#226 RUN-4830 add isMainWindow function
  docs.README.md
  src/api/window/window.ts
  test/window.test.ts
  tutorials/Window.getCurrent.md
  tutorials/Window.getCurrentSync.md
  tutorials/Window.isMainWindow.md
Labels: auto testing done, cla-present

#230 RUN-4644 Add calls to start/quit application
  docs.README.md
  src/api/application/application.ts
Labels: auto testing done, cla-present

#236 switch from git@ to https to fix the travis build
  .gitmodules
Labels: auto testing started, cla-present

#235 RUN-4644 Updated tutorials for start + quit
  tutorials/Application.close.md
  tutorials/Application.create.md
  tutorials/Application.createFromManifest.md
  tutorials/Application.quit.md
  tutorials/Application.run.md
  tutorials/Application.start.md
  tutorials/Application.startFromManifest.md
Labels: auto testing done, cla-present
