Repository HadoukenIO/js-adapter, pull requests merged in 2019-07, with the labels that each got.

#289 RUN-5201: NWI: add docs tutorials for new API / events (partial)
  src/api/events/base.ts
  src/api/events/externalWindow.ts
  src/api/events/window.ts
  src/api/external-window/external-window.ts
  src/api/window/window.ts
  tutorials/ExternalWindow.EventEmitter.md
  tutorials/Window.EventEmitter.md
  tutorials/Window.animate.md
  tutorials/Window.authenticate.md
  tutorials/Window.blur.md
  tutorials/Window.create.md
  tutorials/Window.executeJavaScript.md
  tutorials/Window.getWebWindow.md
  tutorials/Window.showDeveloperTools.md
Labels: auto testing failed, cla-present

#295 Feature/RUN-4864 channel tutorial overhaul
  src/api/interappbus/channel/channels-docs.ts
  tutorials/Channel.connect.md
  tutorials/Channel.create.md
  tutorials/Channel.disconnect.md
  tutorials/Channel.dispatch.md
  tutorials/Channel.middleware.md
  tutorials/Channel.onDisconnection.md
  tutorials/Channel.register.md
  tutorials/Channel.remove.md
  tutorials/Channel.tutorial.md
  tutorials/ChannelMiddleware.afterAction.md
  tutorials/ChannelMiddleware.beforeAction.md
  tutorials/ChannelMiddleware.onError.md
  tutorials/ChannelMiddleware.setDefaultAction.md
  tutorials/ChannelProvider.destroy.md
  tutorials/ChannelProvider.onConnection.md
  tutorials/ChannelProvider.publish.md
Labels: auto testing done, cla-present

#297 Feature/browserview
  src/api/browserview/browserview.ts
  src/api/fin.ts
Labels: auto testing done, cla-present

#299 [RUN-5208] Add test for external connections and nameAlias
  test/external-connection.test.ts
Labels: auto testing done, cla-present

#302 RUN-5286 v2 Api SetBounds will override identity if passed in bounds have a name.
  src/api/application/application.ts
  src/api/window/window.ts
Labels: auto testing done, cla-present

#304 RUN-5355 js docs fix
  package-lock.json
  package.json
Labels: auto testing ignore, documentation, regression, staging

#300 Add performance-report docs
  src/api/events/application.ts
  src/api/events/window.ts
  tutorials/Application.EventEmitter.md
  tutorials/System.EventEmitter.md
  tutorials/Window.EventEmitter.md
Labels: auto testing done, cla-present

#301 RUN-5305 PR Template on the js-adapter repo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto testing done, cla-present

#308 updated autoresize
  src/api/browserview/browserview.ts
Labels: auto testing ignore, cla-present

#309 Merge staging into develop
  src/api/browserview/browserview.ts
Labels: cla-present

#303 RUN-5240 update customeData type to any
  src/api/application/applicationOption.ts
  src/api/external-window/external-window.ts
  src/api/window/window.ts
  src/api/window/windowOption.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#312 Publish version 1.43.1
  package-lock.json
  package.json
Labels: auto testing done, cla-present

#310 [RUN-5436] Stop using generic object types in windowOptions and applicationOptions
  src/api/application/applicationOption.ts
  src/api/window/window.ts
  src/api/window/windowOption.ts
Labels: auto testing done, cla-present
