Repository HadoukenIO/js-adapter, pull requests merged in 2019-09, with the labels that each got.

#330 Doc Fix
  src/api/interappbus/interappbus.ts
  tutorials/InterApplicationBus.subscribe.md
Labels: auto testing ignore

#332 updated subscribe typo, onChannelConnect definition
  src/api/interappbus/channel/channels-docs.ts
  tutorials/InterApplicationBus.subscribe.md
Labels: auto testing failed

#326 RUN-5493: Add nativeId to identity, upgrade tutorial
  src/api/external-window/external-window.ts
  src/identity.ts
  tutorials/ExternalWindow.wrap.md
Labels: auto testing done, cla-present

#339 RUN-5584 - Multi-runtime onDisconnection from ChannelProvider
  src/api/interappbus/channel/client.ts
Labels: auto testing ignore, cla-present

#340 Merge staging into develop
  src/api/interappbus/channel/client.ts
Labels: cla-present

#342 RUN-5608 added view.destroy
  src/api/browserview/browserview.ts
Labels: auto testing done, cla-present

#327 RUN-5469 Added state methods
  src/api/application/application.ts
  src/api/browserview/browserview.ts
  src/api/window/window.ts
  src/transport/transport.ts
Labels: auto testing done, cla-present

#328 Bump to version 1.44.1
  package.json
Labels: auto testing done, cla-present

#344 RVM-976: createFromManifest options
  src/api/application/application.ts
Labels: auto testing ignore, cla-present

#333 RUN-5530 remove access to electron ipc
  src/transport/transport.ts
  test/multi-runtime-utils.ts
  test/uuid-enforcement.test.ts
Labels: auto testing done, cla-present

#346 [N/A] Fix global hotkey api return type comment typo
  src/api/global-hotkey/index.ts
Labels: auto testing done, cla-present

#343 [RUN-5206] Add BrowserView Method Events
  src/api/browserview/browserview.ts
  src/api/events/base.ts
  src/api/events/browserview.ts
  src/api/events/eventAggregator.ts
  src/api/events/webcontents.ts
  src/api/events/window.ts
  src/api/webcontents/webcontents.ts
  tutorials/BrowserView.EventEmitter.md
  tutorials/BrowserView.attach.md
  tutorials/BrowserView.create.md
  tutorials/BrowserView.getInfo.md
  tutorials/BrowserView.hide.md
  tutorials/BrowserView.setBounds.md
  tutorials/BrowserView.show.md
  tutorials/BrowserView.wrapSync.md
Labels: auto testing done, cla-present

#351 RUN-4075 Update setTrayIcon doc
  src/api/application/application.ts
  tutorials/Application.setTrayIcon.md
Labels: auto testing done, cla-present, staging

#348 Align "CONTRIBUTING" section in README.md to FINOS project blueprint
  README.md
Labels: auto testing done, cla-present

#352 [RUN-5626] Emit view-attached and view-detached events from View to Window
  src/api/events/window.ts
  tutorials/Window.EventEmitter.md
Labels: auto testing done, cla-present

#349 [RUN-5625] Propagate events from BrowserView to Application and System
  src/api/events/application.ts
  src/api/events/browserview.ts
  src/api/events/system.ts
  tutorials/Application.EventEmitter.md
  tutorials/System.EventEmitter.md
Labels: auto testing done, cla-present

#350 [RUN-5628] Route WebContents events over to BrowserView
  src/api/events/webcontents.ts
  src/api/events/window.ts
  tutorials/BrowserView.EventEmitter.md
  tutorials/Window.EventEmitter.md
Labels: auto testing done, cla-present

#353 RUN-5647 fix some issues
  src/api/application/application.ts
  src/api/external-window/external-window.ts
  src/api/global-hotkey/index.ts
  src/api/interappbus/channel/channels-docs.ts
  src/api/system/external-process.ts
  src/api/system/installed-runtimes.ts
  src/api/system/system.ts
  tutorials/System.getInstalledRuntimes.md
Labels: auto testing done, cla-present
