Repository HadoukenIO/js-adapter, pull requests merged in 2019-02, with the labels that each got.

#240 RUN-4644 Start from manifest fix
  src/api/application/application.ts
  test/application.test.ts
Labels: auto testing ignore, cla-present

#242 added some shapes that native window integration will need
  src/shapes.ts
Labels: cla-present

#237 RUN-4974 remove --enable-multi-runtime flag
  Gruntfile.js
  test/multi-runtime-utils.ts
Labels: auto testing done, cla-present

#238 RUN-4981-Launch RVM directly, instead of installer
  resources/win/OpenFinInstaller.exe
  resources/win/OpenFinRVM.exe
  src/launcher/launcher.ts
  src/launcher/win-launch.ts
Labels: auto testing done, cla-present

#247 Feature/RUN-4956 flip wait for page load auto show
  src/api/application/application.ts
  src/api/window/window.ts
Labels: auto testing done, cla-present
